# Generated by Django 4.2.18 on 2025-08-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
